version: "3.9"
services:
  ultimateproxy:
    image: bitofsin/ultimateproxy:latest
    container_name: UltimateProxyV2
    
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - <path to host dir>:/config
    ports:
      - 4444:4444
    
    restart: unless-stopped

# please change the volume path on host to save config/data to a location you specify
#port 4444 on container image is set to export in Dockerfile build